.TH "gengo" 1 "2015-09-05" "Linux Command"


.SH NAME

.P
\fBgengo\fR \- generates getoptions subroutine and header.

.SH SYNOPSIS

.P
\fBgengo\fR \-i [option] option_string

.P
\fBgengo\fR \-g [option] program_name

.SH DESCRIPTION

.P
\fBgengo\fR is an interactive program that operates on the
user provided option string and generates
\fIgetoptions.c\fR and \fIgetoptions.h\fR together with a
workable \fImain.c\fR in accordance with the answers given.

.P
The options string output will begin with ":h".
Please make no reference short option h or long option help as
processing for this option is built into the program.
If want to change the wording given for the help option, edit
\fI$HOME.config/gengo/getoptionsBP.c\fR

.P
`make` followed by `./program_name \-h` should get you the
help listing before you add anything to your new program.

.P
On first run the following files will be written to
\fI$HOME/.config/gengo/; //mainBP.c\fR, \fIgetoptionsBP.c\fR, \fIMakefileBP\fR
 and \fIgetoptioBP.h\fR.
You may edit these files as required. However, be aware that there are
many comments of the form \fI//<sometag>\fR on new lines within these
files  that are used as targets during processing.
These should be left alone.

.SH OPTIONS

.TP
 \fB\-h, \-\-help\fR
print help information and exit.

.TP
 **d, \-\-delete
Delete any workfiles found in the current directory.

.TP
 \fB\-i, \-\-interactive\fR
generate intermediate files from the user's answers to
questions about the options.

The files are \fIhelpTXT.c\fR, \fIdeclTXT.h\fR, \fIdefltTXT.c\fR,
\fIsocodeTXT.c\fR, \fIlocodeTXT.c\fR, \fIlostructTXT.c\fR and \fInoargsTXT.c\fR.
These files will be written in the current dir.

.TP
 \fB\-g, generate\fR
generate the \fImain.c\fR, \fIgetoptions.c\fR and
\fIgetoptions.h\fR. from the above named txt files. Generate
a \fIMakefile\fR to make \fIprogram_name\fR.

The next option is only meaningful when using \-g option.

.TP
 \fB\-c, \-\-columns\fR
number of columns in display. Default is 80 columns.
If altered the columns should be in range 72..132. If outside the value
will be altered to bring it into range.

.P
By making this a 2 stage process, the user has the
opportunity to edit the text files if required before
program generation.

.SH AUTHOR

.P
Robert L Parker rlp1938@gmail.com

.SH SEE ALSO

.P
\fBgetopt\fR (3)

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -t man gengo.t2t
