.TH "gengo" 1 "2015-06-18" "Linux Command"


.SH NAME

.P
\fBgengo\fR \- generates getoptions subroutine and header.

.SH SYNOPSIS

.P
\fBgengo\fR \-i [option] option_string

.P
\fBgengo\fR \-g [option] program_name

.SH DESCRIPTION

.P
\fBgengo\fR is an interactive program that operates on the
user provided option string and generates
\fIgetoptions.c\fR and \fIgetoptions.h\fR together with a
workable \fImain.c\fR in accordance with the answers given.

.P
The options string output will begin with ":h". You may
preface your provided options string with this or not as you
wish. If not provided the program will do it.

.P
`make` followed by `./program_name \-h` should get you the
help listing before you add anything to your new program.

.P
On first run the following files will be written to
\fI$HOME/.config/gengo/; //main.bp\fR, \fImainhdr.bp\fR,
\fIgetoptions.bp\fR, and \fIgetoptions.bp\fR. You may edit these
files as required.

.SH OPTIONS

.TP
 \fB\-h\fR
print help information and exit.

.TP
 \fB\-i\fR
generate intermediate files from the user's answers to
questions about the options.

The files are \fIhelptext.txt\fR, \fIdeclare.txt\fR, \fIdefault.txt\fR
and \fIcode.txt\fR. These files will be written in the current dir.

.TP
 \fB\-l\fR
ask for long option names and generate code to process them. This is
meaningful only with \-i option.

.TP
 \fB\-g\fR
generate the \fImain.c\fR, \fIgetoptions.c\fR and
\fIgetoptions.h\fR. from the above named txt files. Generate
a \fIMakefile\fR to make \fIprogram_name\fR.

The next options are only meaningful when using \-g option.

.TP
 \fB\-c\fR
number of columns in display. Default is 80 columns.

.TP
 \fB\-s\fR
starting column for help text. Default is 12, ie 12 spaces from the left.

.TP
 \fB\-u\fR
starting column for usage text. Default is 16, ie 2 tabs from the left.

.P
By making this a 2 stage process, the user has the
opportunity to edit the text files if required before
program generation.

.SH AUTHOR

.P
Robert L Parker rlp1938@gmail.com

.SH SEE ALSO

.P
\fBwhatever\fR (1)

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -t man gengo.t2t
